#!/usr/bin/env python

import argparse
import sys
import os.path
import hashlib
from Crypto.Cipher import AES
from Crypto import Random

HARDCODED_STRING = "e6f5bfbaae81a4496b5489f"

def handle_options(options, log_data=None):
    minimum_timestamp = 0
    if options.timestamp <= 0:
        # timestamps must be positive
        sys.stdout.write('invalid')
        return -1

    # if log_data:
    #     most_recent_time = log_data[-1].split(' ')[0]
    #     if options.timestamp <= most_recent_time:
    #         sys.stdout.write('invalid')
    #         return -1

    # we need to return the data that we want encrypted here
    return 'swag'

def encrypt_to_file(f, data, options):
    nonce = Random.new().read(AES.block_size)
    message = HARDCODED_STRING + "\n" + data

    # encrypted under the -K option passed in as a 256 hash
    key = hashlib.sha256(options.token).digest()

    obj = AES.new(key, AES.MODE_CFB, nonce)
    ciphertext = obj.encrypt(message)

    # first line of file is unencrypted nonce, 2nd line is encrypted
    # first line of encrypted is the hardcoded string, rest is log data
    f.write(nonce + "\n" + ciphertext)

def handle_single_command(options):
    log_path = options.log

    if log_path == None:
        # we need the last argument to be the path to log
        sys.stdout.write('invalid')
        return -1

    if os.path.isfile(log_path):
        # appending to an existing log
        f=open(log_path, 'r+w')
        lines = f.readlines()
        nonce = lines[0].rstrip() # remove new line

        ciphertext = lines[1].rstrip() # remove new line char

        # decrypted under the -K option passed in as a 256 hash
        key = hashlib.sha256(options.token).digest()
        obj = AES.new(key, AES.MODE_CFB, nonce)

        message = obj.decrypt(ciphertext)
        data = message.splitlines()
        if data[0] != HARDCODED_STRING:
            # token was not correct if it didn't decrypt
            # to the hardcoded string properly
            sys.stderr.write("security error")
            return -1

        data = handle_options(options, data[1:])
        encrypt_to_file(f, data, options)
    else:
        f=open(log_path, 'w')
        # this is a new log

        data = handle_options(options)

        encrypt_to_file(f, data, options)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("-T", type=int, dest="timestamp")
    parser.add_argument("-K", dest="token")
    parser.add_argument("-E", dest="employee_name")
    parser.add_argument("-G", dest="guest_name")
    parser.add_argument("-A", dest="arrival", action='store_true')
    parser.add_argument("-L", dest="departure", action='store_true')
    parser.add_argument("-R", type=int, dest="room_id")
    parser.add_argument("-B", dest="file")
    parser.add_argument("log", help='string for log path')

    options = parser.parse_args()

    # TODO handle the -B option

    handle_single_command(options)


if __name__ == "__main__":
    main()

