#!/usr/bin/env python

from optparse import OptionParser

def main():
    parser = OptionParser()
    parser.add_option("-H", action='store_true', dest="html")
    parser.add_option("-K", dest="token")

    (options, args) = parser.parse_args()

    # TODO - actually do this


if __name__ == "__main__":
    main()